"""add_stamina_and_radiation_fields

Revision ID: fe5cdadcdab6
Revises: e20a2ace2721
Create Date: 2025-05-29 15:11:45.707041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5cdadcdab6'
down_revision = 'e20a2ace2721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('stamina', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('radiation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'radiation')
    op.drop_column('players', 'stamina')
    # ### end Alembic commands ###
